config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
  resources :habits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/habit.rb
class Habit < ApplicationRecord
  validates :name, presence: true, uniqueness: { scope: :user_id, message: "You already have a habit with this name." }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable

  has_many :habits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_habit, only: %w[show edit update destroy]

  def index
    @habits = current_user.habits.all
  end

  def new
    @habit = current_user.habits.new
  end

  def create
    @habit = current_user.habits.new(habit_params)
    if (@habit.save)
      redirect_to habits_path, notice: "Hooray!🥳 Your new habit was created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show

  end

  def edit
  end

  def update
    if @habit.update(habit_params)
      redirect_to @habit, notice: "Your habit was updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @habit.destroy()
      redirect_to habits_path, notice: "Habit was deleted!"
    else
      render :edit, status: :unprocessable_entity
    end
  end


  private

  def habit_params
    params.require(:habit).permit(:name)
  end

  def find_habit
    @habit = current_user.habits.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to habits_path
    else
      render :home
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/habits_helper.rb
module HabitsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/habits/_confirm_delete_modal.html.erb
<dialog id="my_modal_1" class="modal">
  <div class="modal-box">
    <h3 class="text-lg font-bold">Are you sure you want to delete this habit?</h3>
    <p class="py-4">This action cannot be undone.</p>
    <div class="modal-action">
      <form method="dialog" class="flex gap-4">
        <%= link_to 'Confirm', habit_path(@habit), data: { "turbo_method": :delete }, class: "btn text-red-500" %>
        <button class="btn">Close</button>
      </form>
    </div>
  </div>
</dialog>

app/views/habits/_form.html.erb
<div class="w-full flex justify-center mt-4">
  <div class="card bg-base-100 w-full max-w-sm shrink-0 shadow-2xl">
    <div class="card-body">
      <%= form_with model: @habit do |form| %>
        <div class="form-control">
          <%= form.label :name, class: "label" do %>
            <span class="label-text">Habit name</span>
          <% end %>
          <%= form.text_field :name, class: "input input-bordered w-full", placeholder: "Your new habit name" %>
          <% if !@habit.errors.full_messages.empty? %>
            <div class="text-rose-500 text-sm mt-1"><%= @habit.errors.full_messages.join(', ') %></div>
          <% end %>
        </div>
        <div class="form-control mt-6">
          <%= form.submit "Create", class: "btn btn-primary" %>
        </div>
      <% end %>
      <% if action_name == "edit" %>
        <div class="form-control mt-6">
          <button class="link text-red-500" method="dialog" onclick="my_modal_1.showModal()">Delete</button>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if action_name == "edit" %>
  <%= render "confirm_delete_modal" %>
<% end %>

app/views/habits/_habit.html.erb
<div class="card bg-base-100 shadow-xl max-w-md w-full">
  <div class="card-body">
    <h2 class="card-title"><%= habit.name %></h2>
    <p>Habit description</p>
    <div class="card-actions justify-between items-center">
      <div class="flex gap-2">
        <% if action_name == "index" %>
          <%= link_to'Show', habit, class: "link link-primary" %>
        <% end %>
        <%= link_to "Edit", edit_habit_path(habit), class: "link link-primary" %>
      </div>
      <button class="btn btn-primary">Complete</button>
    </div>
  </div>
</div>

app/views/habits/edit.html.erb
<h1 class="text-center text-2xl">Edit habit</h1>
<%= render 'form' %>

app/views/habits/index.html.erb
<h1 class="text-center text-2xl">Habits</h1>
<% if @habits.empty? %>
  <div class="h-96 flex flex-col items-center justify-center">
    <h2 class="text-center text-xl">You don't have any habits yet.</h2>
    <%= link_to 'Let\'s create the one', new_habit_path, class: "mt-4 link link-primary" %>
  </div>
<% end %>
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
  <%= render @habits %>
</div>

app/views/habits/new.html.erb
<h1 class="text-center text-2xl">Let's create New Habit</h1>
<%= render 'form' %>

app/views/habits/show.html.erb
<h1 class="text-center text-2xl">View</h1>
<div class="flex justify-center w-full">
  <%= render @habit %>
</div>

app/views/layouts/_navigation.html.erb
<div class="navbar bg-base-100">
  <div class="flex-1">
    <%= link_to '🚀 Routin Rocket', root_path, class: "btn btn-ghost text-xl" %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
      <% if user_signed_in? %>
        <li>
          <details class="relative">
            <summary class="cursor-pointer">My Habits</summary>
            <ul class="absolute bg-base-100 p-2 mt-2 z-50 rounded-box shadow">
              <li><%= link_to "Create", new_habit_path %></li>
              <li><%= link_to "Review", habits_path %></li>
            </ul>
          </details>
        </li>
      <% end %>
      <% if !user_signed_in? %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <% end %>
    </ul>

    <% if user_signed_in? %>
      <div class="dropdown dropdown-end">
        <div tabindex="0" role="button" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img
              alt="Tailwind CSS Navbar component"
              src="https://img.daisyui.com/images/stock/photo-1534528741775-53994a69daeb.webp" />
          </div>
        </div>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content bg-base-100 rounded-box z-50 mt-3 w-52 p-2 shadow">
          <li>
            <%= link_to "Profile", edit_user_registration_path(current_user) %>
          </li>
          <li><%= link_to "Log Out", destroy_user_session_path, data: { "turbo-method": :delete } %></li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutinRocket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
  </head>
  <body>
    <main class="container mx-auto px-5">
      <%= render 'layouts/navigation' %>
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<!-- Hero Section -->
<div class="hero min-h-screen" style="background-image: url('<%= asset_path("jumbotron.jpg") %>');">
  <div class="hero-overlay bg-opacity-70"></div>
  <div class="hero-content text-center text-neutral-content">
    <div class="max-w-lg">
      <h1 class="mb-5 text-5xl font-bold">Welcome to <br>
        Routine Rocket</h1>
      <p class="mb-5">The Road to your dream life</p>
      <%= link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</div>
<!-- Features Section -->
<section class="container mx-auto my-16 px-4">
  <div class="text-center mb-12">
    <h2 class="text-4xl font-bold">Our Features</h2>
    <p class="mt-4">Discover the amazing features that make us the best choice for you.</p>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h3 class="card-title">Simple and Intuitive Interface</h3>
        <p>No Overwhelm, Just Progress:  Stay focused with a clear and simple layout that helps you achieve your goals.</p>
      </div>
      <figure>
        <img src="<%= asset_path("simple.jpg") %>" alt="Feature One" />
      </figure>
    </div>
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h3 class="card-title">Create Positive or Break Negative Habits</h3>
        <p>Tailored Habit Management: Build healthy routines or eliminate bad ones with custom habit types</p>
      </div>
      <figure>
        <img src="<%= asset_path("positive-habit.jpg") %>" alt="Feature Two" />
      </figure>
    </div>
    <div class="card bg-base-100 shadow-xl">
      <div class="card-body">
        <h3 class="card-title">Reflect and Improve</h3>
        <p>Learn From Your Journey: Keep track of your mindset and motivations to better understand your path to success.</p>
      </div>
      <figure>
        <img src="<%= asset_path("reflect.jpg") %>" alt="Feature Three" />
      </figure>
    </div>
  </div>
</section>
<!-- Call to Action Section -->
<section class="hero bg-base-200 py-20">
  <div class="hero-content text-center">
    <div class="max-w-lg">
      <h2 class="text-4xl font-bold mb-5">Ready to Get Started?</h2>
      <p class="mb-5">Join us today and take the first step towards better productivity.</p>
      <%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
</section>
<!-- Footer -->
<footer class="bg-base-100 text-neutral-content p-4">
  <div class="container mx-auto flex justify-between items-center">
    <p>&copy; 2024 YourBrand. All rights reserved.</p>
    <div class="space-x-4">
      <a href="#">Privacy Policy</a>
      <a href="#">Terms of Service</a>
    </div>
  </div>
</footer>

app/views/shared/_flash_messages.html.erb
<% if notice %>
  <div 
    role="alert" 
    class="toast toast-top toast-end items-center justify-between transition transform duration-2000 hidden"
    data-controller="notification"
    data-notification-delay-value="2000"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
  >
    <div class="alert alert-success">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6 shrink-0 stroke-current inline-block mr-2"
        fill="none"
        viewBox="0 0 24 24">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      <span><%= notice %></span>
      <button type="button" data-action="notification#hide">
        <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6 shrink-0 stroke-current inline-block mr-2"
        fill="none"
        viewBox="0 0 24 24">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      </button>
    </div>
  </div>
<% end %>

<% if alert %>
  <div 
    role="alert" 
    class="toast toast-top toast-end items-center justify-between transition transform duration-4000 hidden"
    data-controller="notification"
    data-notification-delay-value="4000"
    data-transition-enter-from="opacity-0 translate-x-6"
    data-transition-enter-to="opacity-100 translate-x-0"
    data-transition-leave-from="opacity-100 translate-x-0"
    data-transition-leave-to="opacity-0 translate-x-6"
  >
    <div class="alert bg-red-500">
      <span><%= alert %></span>
      <button type="button" data-action="notification#hide">
        <svg
        xmlns="http://www.w3.org/2000/svg"
        class="h-6 w-6 shrink-0 stroke-current inline-block mr-2"
        fill="none"
        viewBox="0 0 24 24">
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          stroke-width="2"
          d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
      </svg>
      </button>
    </div>
  </div>
<% end %>